config/routes.rb
Rails.application.routes.draw do
  resources :sellers do
    resources :service_orders
    resources :seller_charges
  end
  resources :seller_companies

  root 'sellers#index'

end

app/models/seller_company.rb
class SellerCompany < ActiveRecord::Base

	has_many :sellers, dependent: :nullify
	
end

app/controllers/seller_companies_controller.rb
class SellerCompaniesController < ApplicationController
  before_action :set_seller_company, only: [:show, :edit, :update, :destroy]

  # GET /seller_companies
  # GET /seller_companies.json
  def index
    @seller_companies = SellerCompany.all
  end

  # GET /seller_companies/1
  # GET /seller_companies/1.json
  def show
  end

  # GET /seller_companies/new
  def new
    @seller_company = SellerCompany.new
  end

  # GET /seller_companies/1/edit
  def edit
  end

  # POST /seller_companies
  # POST /seller_companies.json
  def create
    @seller_company = SellerCompany.new(seller_company_params)

    respond_to do |format|
      if @seller_company.save
        format.html { redirect_to @seller_company, notice: 'Seller company was successfully created.' }
        format.json { render :show, status: :created, location: @seller_company }
      else
        format.html { render :new }
        format.json { render json: @seller_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seller_companies/1
  # PATCH/PUT /seller_companies/1.json
  def update
    respond_to do |format|
      if @seller_company.update(seller_company_params)
        format.html { redirect_to @seller_company, notice: 'Seller company was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller_company }
      else
        format.html { render :edit }
        format.json { render json: @seller_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seller_companies/1
  # DELETE /seller_companies/1.json
  def destroy
    @seller_company.destroy
    respond_to do |format|
      format.html { redirect_to seller_companies_url, notice: 'Seller company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller_company
      @seller_company = SellerCompany.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_company_params
      params[:seller_company]
    end
end

app/helpers/seller_companies_helper.rb
module SellerCompaniesHelper
end

app/views/seller_companies/_form.html.erb
<%= form_for(@seller_company) do |f| %>
  <% if @seller_company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller_company.errors.count, "error") %> prohibited this seller_company from being saved:</h2>

      <ul>
      <% @seller_company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seller_companies/edit.html.erb
<h1>Editing Seller Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @seller_company %> |
<%= link_to 'Back', seller_companies_path %>

app/views/seller_companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Seller Companies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seller_companies.each do |seller_company| %>
      <tr>
        <td><%= link_to 'Show', seller_company %></td>
        <td><%= link_to 'Edit', edit_seller_company_path(seller_company) %></td>
        <td><%= link_to 'Destroy', seller_company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller company', new_seller_company_path %>

app/views/seller_companies/new.html.erb
<h1>New Seller Company</h1>

<%= render 'form' %>

<%= link_to 'Back', seller_companies_path %>

app/views/seller_companies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_seller_company_path(@seller_company) %> |
<%= link_to 'Back', seller_companies_path %>