config/routes.rb
Rails.application.routes.draw do
  resources :sellers do
    resources :service_orders
    resources :seller_charges
  end
  resources :seller_companies

  root 'sellers#index'

end

app/models/service_order.rb
class ServiceOrder < ActiveRecord::Base

	belongs_to :seller

end

app/controllers/service_orders_controller.rb
class ServiceOrdersController < ApplicationController
  before_action :set_service_order, only: [:show, :edit, :update, :destroy]

  # GET /service_orders
  # GET /service_orders.json
  def index
    @seller = Seller.find(params[:seller_id])
    @service_orders = @seller.service_orders
  end

  # GET /service_orders/1
  # GET /service_orders/1.json
  def show
  end

  # GET /service_orders/new
  def new
    @service_order = ServiceOrder.new
  end

  # GET /service_orders/1/edit
  def edit
  end

  # POST /service_orders
  # POST /service_orders.json
  def create
    @service_order = ServiceOrder.new(service_order_params)

    respond_to do |format|
      if @service_order.save
        format.html { redirect_to @service_order, notice: 'Service order was successfully created.' }
        format.json { render :show, status: :created, location: @service_order }
      else
        format.html { render :new }
        format.json { render json: @service_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_orders/1
  # PATCH/PUT /service_orders/1.json
  def update
    respond_to do |format|
      if @service_order.update(service_order_params)
        format.html { redirect_to @service_order, notice: 'Service order was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_order }
      else
        format.html { render :edit }
        format.json { render json: @service_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_orders/1
  # DELETE /service_orders/1.json
  def destroy
    @service_order.destroy
    respond_to do |format|
      format.html { redirect_to service_orders_url, notice: 'Service order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_order
      @service_order = ServiceOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_order_params
      params[:service_order]
    end
end

app/helpers/service_orders_helper.rb
module ServiceOrdersHelper
end

app/views/service_orders/_form.html.erb
<%= form_for(@service_order) do |f| %>
  <% if @service_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_order.errors.count, "error") %> prohibited this service_order from being saved:</h2>

      <ul>
      <% @service_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_orders/edit.html.erb
<h1>Editing Service Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_order %> |
<%= link_to 'Back', service_orders_path %>

app/views/service_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Service Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_orders.each do |service_order| %>
      <tr>
	<td><%= service_order.name %></td>
        <td><%= link_to 'Show', seller_service_order_path(seller_id: @seller.id, id: service_order.id) %></td>
        <td><%= link_to 'Edit', edit_seller_service_order_path(seller_id: @seller.id, id: service_order) %></td>
        <td><%= link_to 'Destroy', "/sellers/#{@seller.id}/service_orders/#{service_order.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service order', new_seller_service_order_path %>

app/views/service_orders/new.html.erb
<h1>New Service Order</h1>

<%= render 'form' %>

<%= link_to 'Back', service_orders_path %>

app/views/service_orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_service_order_path(@service_order) %> |
<%= link_to 'Back', service_orders_path %>