config/routes.rb
Rails.application.routes.draw do
  resources :sellers do
    resources :service_orders
    resources :seller_charges
  end
  resources :seller_companies

  root 'sellers#index'

end

app/models/seller_charge.rb
class SellerCharge < ActiveRecord::Base
end

app/controllers/seller_charges_controller.rb
class SellerChargesController < ApplicationController
  before_action :set_seller_charge, only: [:show, :edit, :update, :destroy]

  # GET /seller_charges
  # GET /seller_charges.json
  def index
    @seller = Seller.find(params[:seller_id])
    @seller_charges = @seller.seller_charges
  end

  # GET /seller_charges/1
  # GET /seller_charges/1.json
  def show
  end

  # GET /seller_charges/new
  def new
    @seller_charge = SellerCharge.new
  end

  # GET /seller_charges/1/edit
  def edit
  end

  # POST /seller_charges
  # POST /seller_charges.json
  def create
    @seller_charge = SellerCharge.new(seller_charge_params)

    respond_to do |format|
      if @seller_charge.save
        format.html { redirect_to @seller_charge, notice: 'Seller charge was successfully created.' }
        format.json { render :show, status: :created, location: @seller_charge }
      else
        format.html { render :new }
        format.json { render json: @seller_charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seller_charges/1
  # PATCH/PUT /seller_charges/1.json
  def update
    respond_to do |format|
      if @seller_charge.update(seller_charge_params)
        format.html { redirect_to @seller_charge, notice: 'Seller charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller_charge }
      else
        format.html { render :edit }
        format.json { render json: @seller_charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seller_charges/1
  # DELETE /seller_charges/1.json
  def destroy
    @seller_charge.destroy
    respond_to do |format|
      format.html { redirect_to seller_charges_url, notice: 'Seller charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller_charge
      @seller_charge = SellerCharge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_charge_params
      params[:seller_charge]
    end
end

app/helpers/seller_charges_helper.rb
module SellerChargesHelper
end

app/views/seller_charges/_form.html.erb
<%= form_for(@seller_charge) do |f| %>
  <% if @seller_charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller_charge.errors.count, "error") %> prohibited this seller_charge from being saved:</h2>

      <ul>
      <% @seller_charge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seller_charges/edit.html.erb
<h1>Editing Seller Charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @seller_charge %> |
<%= link_to 'Back', seller_charges_path %>

app/views/seller_charges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Seller Charges</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seller_charges.each do |seller_charge| %>
      <tr>
        <td><%= link_to 'Show', seller_seller_charge_path(seller_id: @seller.id, id: seller_charge.id) %></td>
        <td><%= link_to 'Edit', edit_seller_seller_charge_path(seller_id: @seller.id, id: seller_charge.id) %></td>
        <td><%= link_to 'Destroy', "/sellers/#{@seller}/seller_charges/#{seller_charge.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller charge', new_seller_seller_charge_path %>

app/views/seller_charges/new.html.erb
<h1>New Seller Charge</h1>

<%= render 'form' %>

<%= link_to 'Back', seller_charges_path %>

app/views/seller_charges/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_seller_charge_path(@seller_charge) %> |
<%= link_to 'Back', seller_charges_path %>